- name: install basic packages for ubuntu
  ansible.builtin.apt:
    name:
      - git
      - net-tools
      - iputils-ping
      - dnsutils
      - wget
      - curl
      - vim
      - unzip
      - screen
      - tmux
      - htop
      - tree
      - jq
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - libxml2-dev
      - libxslt1-dev
      - libjpeg-dev
      - libpq-dev
